### ISSUE TITLE
Playback of music on local music folder via Elisa etc is not stable and the music keeps jumping

### ISSUE THREAD

**Issue by jsarkari** [manjaro-pinephone/plasma-mobile-dev#11]
I have also tested this on the stable build and the same thing is happening. Whether via internal speaker, headphones or bluetooth.

I have also tried apps like Shortwave etc and the same thing happens.

I also tried turning off bluetooth, wifi to see if this would help but no difference.

**Comment by Strit** [comment]
Are you running from SD card?

I can reproduce on an SD card, but not on the internal storage.

**Comment by jsarkari** [comment]
Yes I have been trying out different distros and flavours to see which is best.

Currently I have come to the conclusion that phosh manjaro and phosh arch linux are the best to run for now on the ppp.
________________________________

**Comment by jsarkari** [comment]
I no longer have the mobile so unable to retest further.
