### ISSUE TITLE
Unable to install certain music apps via terminal or discover

### ISSUE THREAD

**Issue by jsarkari** [manjaro-pinephone/plasma-mobile-dev#12]
Unable to process... message and unable to find repository.

Was able to install (shortwave, vlc etc) on stable build but having trouble here.

This also is including Libre apps also.

**Comment by Strit** [comment]
What applications / packages specifically?

They need to be either in our repository or have an aarch64 flatpak available.

**Comment by jsarkari** [comment]
I have problems with Shortwave.

Cannot seem to run on ppp only on PC via Linux Mint for example.
________________________________

**Comment by Strit** [comment]
Shortwave is not in our repository. It is in the AUR though.
