### ISSUE TITLE
Opening Keyboard on PPP crashes wayland server

### ISSUE THREAD

**Issue by aimad10** [manjaro-pinephone/plasma-mobile-dev#13]
Whenever I try to access on screen keyboard, it crashes the entire server. I can't copy and paste the core dumps because I can't output them to a text file without a onscreen keyboard, and the Crash Reporter app is not scrollable. 

Here are the screenshots what I was able to make; I'll try and just convert the current pages to a scrollable page so this isn't a problem in the future. 
[imagesofcoredumps.zip](https://github.com/manjaro-pinephone/plasma-mobile-dev/files/8484306/imagesofcoredumps.zip)

**Comment by dobey** [comment]
This is already reported upstream at https://invent.kde.org/teams/plasma-mobile/issues/-/issues/143

**Comment by aimad10** [comment]
Sorry, I thought this was the main development forum! Was wondering why it was so dry.
