### ISSUE TITLE
On startup this latest build 20200606 keeps returning to the setup screen

### ISSUE THREAD

**Issue by jsarkari01** [manjaro-pinephone/plasma-mobile-dev#15]
Everytime I reboot on PPP to this build installed on SD card yesterday it starts up with the setup "Welcome" page and have to at least put in the timezone to then get back to the home screen.

However I then get a message to say the updates failed.

I checked for updates via the terminal: sudo pacman -Syu and there were no updates available.

**Comment by Strit** [comment]
This was fixed in newer images.
