### ISSUE TITLE
klockscreen broken

### ISSUE THREAD

**Issue by rehejuhan** [manjaro-pinephone/plasma-mobile-dev#18]
Manjaro-ARM-plasma-mobile-dev-pinephone-20220930.img
After passing the firstrun wizard, it boots to broken lockscreen.
Lockscreen seems to be broken also on desktop Plasma.

**Comment by Strit** [comment]
It seems to be an issue with one of the framework 5.98 packages. I just don't have any idea which and what to patch to fix it.

**Comment by Strit** [comment]
I just uploaded a new version of `layer-shell-qt` which fixed this issue for me.

So an update or tomorrows image should have working lockscreen again.

**Comment by Strit** [comment]
Depends on when your mirrors sync.

**Comment by Strit** [comment]
Yes. https://invent.kde.org/teams/plasma-mobile/issues/-/issues/182
