### ISSUE TITLE
Manjaro-ARM-plasma-mobile-dev-pinephone-20221016.img - some issues

### ISSUE THREAD

**Issue by rehejuhan** [manjaro-pinephone/plasma-mobile-dev#19]
Great to see again top/bottom panels :)
Some issues:
1. After boot until homescreen everything are small (scaling 100%): baloo error window; firstrun wizard; lockscreen; sim pin unlocking window. Homescreen is ok (200%) and after that also lockscreen is ok.
2. When in lockscreen it is possible to use the top pulldown menu. Shouldn't it be restricted, when device is locked, to perform tasks like switching on/off flashlight, wireless/mobile broadband connection or switch off the whole device?
3. When device is locked, it is quite impossible to answer the call.

**Comment by Strit** [comment]
1. Cannot replicate. Most stuff is blurry, like it's scaling wrong, but it's not tiny.
2. The lockscreen has acted this way for a while. Seems to be a design decision from the devs.
3. This was suppose to be working with Plasma 5.26 and Plasma Dialer 22.09. I wonder why it's not...
