### ISSUE TITLE
ModemManager-Dev 202111020249 does not boot to desktop

### ISSUE THREAD

**Issue by rehejuhan** [manjaro-pinephone/plasma-mobile-dev#5]
Current behaviour: animated KDE logo -> still KDE logi -> screen refreshes -> again still KDE logo forever.
Expected behaviour: boot to first run wizard

**Comment by Strit** [comment]
Same happens on normal dev image. But not on the non-dev image, so this seems to be an issue with the Plasma git master stack.

Happens sometimes. That's why we have these dev images.

**Comment by rehejuhan** [comment]
ModemManager-Dev 202111030247 - no change, still KDE logo forever.
The last one that worked was ModemManager-Dev 202111010249, however it booted to first-run wizard at second attempt and after completing that needed one more forced restart to boot to desktop. I liked the simplified settings application and modemmanager part seemed to work ok also. Is there any schedule to move that also to non-devel images?

**Comment by Strit** [comment]
So the last working images are from November 1st. That's good to know.

The "have to hard reboot" after first setup is a known issue on the dev images. It's like sddm has issues restarting.

The Plasma Mobile development team plans to have all the modemmanager stuff working in Plasma Gear Mobile 21.11.

**Comment by rehejuhan** [comment]
ModemManager-Dev 202111040249 starts now to first setup and after finishing it needed a reboot to start to the desktop.
Calling part does not seem to work but SMS sending and receiving is OK.
