### ISSUE TITLE
Display brightness stopped working on the 2021-12-05 build

### ISSUE THREAD

**Issue by dflag84** [manjaro-pinephone/plasma-mobile-dev#6]
The brightness slidebar in the top menu is not functional anymore. It's there but when moved nothing changes. And the display is always set at medium brightness.

**Comment by Strit** [comment]
I can not reproduce this. Is this still the case for you on newer Dev images?

**Comment by magdesign** [comment]
brightness slider works on pinephonepro
kde plasma version 5.24.2
image build [202202280250](https://github.com/manjaro-pinephone/plasma-mobile-dev/releases/tag/202202280250)
