### ISSUE TITLE
Setup wizard no longer runs on fresh install since version 202112030855

### ISSUE THREAD

**Issue by kpmelvin** [manjaro-pinephone/plasma-mobile-dev#7]
This first started happening with version 202112030855

**Comment by philmmanjaro** [comment]
Yes, it is a known issue with the dev-image.

**Comment by rehejuhan** [comment]
Workaround is to run "pico-wizard" from the Terminal :)

**Comment by kpmelvin** [comment]
> Workaround is to run "pico-wizard" from the Terminal :)

Nice, that worked. Thx rehejuhan!

**Comment by Strit** [comment]
The wizard now runs after the Plasma Mobile session is up.
