### ISSUE TITLE
Latest releases boot to lockscreen instead of first run wizard

### ISSUE THREAD

**Issue by rehejuhan** [manjaro-pinephone/plasma-mobile-dev#9]
Tested 2 latest releases:
Developer Release 202202180249 booted to lockscreen instead of first run wizaed. Fortunately the default password (123456) worked and the wizaed started after that. Unfortunately applying updates and rebooting results a lockscreen and inserting your password results a message that unlocking failed and suggested to switch to another terminal etc...
Developer Release 202202200248 boots to lockscreen and after inserting the default password the result is as the previous release with updates - unable to unlock the session...

**Comment by philmmanjaro** [comment]
Please check if the following works again: https://github.com/manjaro-pinephone/plasma-mobile-dev/releases/tag/202202210245

**Comment by rehejuhan** [comment]
Yes, it is better in the sense, that now it is possible to unlock the session. Still boots to lockscreen and you have to use default password to unlock and see the first run wizard. On-scrren keyboard is a little off-screen and Settings -> Onscreen keyboard does not start, but this is already another topic...
